// <auto-generated />
using System;
using ETL.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETL.Migrations
{
    [DbContext(typeof(ETLDbContext))]
    [Migration("20251111140224_Add_ComputedTimeSpentTraveling_Column")]
    partial class Add_ComputedTimeSpentTraveling_Column
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ETL.Infrastructure.DataBase.Entities.ETLEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<double>("FareAmount")
                        .HasColumnType("float");

                    b.Property<int>("PULocationId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<bool>("StoreAndForwardFlag")
                        .HasColumnType("bit");

                    b.Property<int>("TimeSpentTraveling")
                        .HasColumnType("int");

                    b.Property<double>("TipAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("TpepDropoffDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TpepPickupDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TripDistance")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ETLEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
